#!/bin/bash

###############################################################################
# Trading Bot VM Deployment - Database Setup Script
# Deskripsi: Setup PostgreSQL database untuk trading bot
# Usage: sudo bash setup-database.sh
###############################################################################

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Trading Bot Database Setup${NC}"
echo -e "${GREEN}========================================${NC}"

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}Error: This script must be run as root (use sudo)${NC}"
   exit 1
fi

# Database configuration
DB_NAME="trading_bot"
DB_USER="trading_user"
DB_PASSWORD=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-25)

echo -e "\n${YELLOW}Creating database and user...${NC}"

# Create database and user
sudo -u postgres psql <<EOF
-- Drop existing database and user if exists
DROP DATABASE IF EXISTS ${DB_NAME};
DROP USER IF EXISTS ${DB_USER};

-- Create new user
CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';

-- Create database
CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};

-- Grant privileges
GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};

-- Connect to the database and grant schema privileges
\c ${DB_NAME}
GRANT ALL ON SCHEMA public TO ${DB_USER};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${DB_USER};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${DB_USER};

-- Exit
\q
EOF

echo -e "${GREEN}✓ Database created successfully${NC}"

# Save database credentials
CREDENTIALS_FILE="/root/.trading-bot-credentials"
cat > $CREDENTIALS_FILE <<EOF
# Trading Bot Database Credentials
# Generated on: $(date)

DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@localhost:5432/${DB_NAME}
EOF

chmod 600 $CREDENTIALS_FILE

echo -e "\n${GREEN}Database credentials saved to: $CREDENTIALS_FILE${NC}"

# Configure PostgreSQL to allow local connections
echo -e "\n${YELLOW}Configuring PostgreSQL...${NC}"

PG_VERSION=$(psql --version | grep -oP '\d+' | head -1)
PG_HBA="/etc/postgresql/${PG_VERSION}/main/pg_hba.conf"

# Backup original pg_hba.conf
cp $PG_HBA ${PG_HBA}.backup

# Update pg_hba.conf to allow password authentication
cat > $PG_HBA <<EOF
# PostgreSQL Client Authentication Configuration File
# Generated by Trading Bot deployment script

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     peer
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
host    all             all             0.0.0.0/0               md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     peer
host    replication     all             127.0.0.1/32            md5
host    replication     all             ::1/128                 md5
EOF

# Restart PostgreSQL
systemctl restart postgresql

echo -e "${GREEN}✓ PostgreSQL configured${NC}"

# Test database connection
echo -e "\n${YELLOW}Testing database connection...${NC}"
if PGPASSWORD=$DB_PASSWORD psql -U $DB_USER -d $DB_NAME -h localhost -c "SELECT 1;" > /dev/null 2>&1; then
    echo -e "${GREEN}✓ Database connection successful${NC}"
else
    echo -e "${RED}✗ Database connection failed${NC}"
    exit 1
fi

# Setup automated backups
echo -e "\n${YELLOW}Setting up automated backups...${NC}"

BACKUP_DIR="/var/backups/trading-bot"
mkdir -p $BACKUP_DIR
chmod 700 $BACKUP_DIR

# Create backup script
cat > /usr/local/bin/backup-trading-bot-db.sh <<EOF
#!/bin/bash
# Trading Bot Database Backup Script

BACKUP_DIR="/var/backups/trading-bot"
DATE=\$(date +%Y%m%d_%H%M%S)
BACKUP_FILE="\${BACKUP_DIR}/trading_bot_\${DATE}.sql.gz"

# Create backup
PGPASSWORD="${DB_PASSWORD}" pg_dump -U ${DB_USER} -h localhost ${DB_NAME} | gzip > \$BACKUP_FILE

# Keep only last 7 days of backups
find \$BACKUP_DIR -name "trading_bot_*.sql.gz" -mtime +7 -delete

echo "Backup completed: \$BACKUP_FILE"
EOF

chmod +x /usr/local/bin/backup-trading-bot-db.sh

# Add cron job for daily backups at 2 AM
(crontab -l 2>/dev/null; echo "0 2 * * * /usr/local/bin/backup-trading-bot-db.sh >> /var/log/trading-bot-backup.log 2>&1") | crontab -

echo -e "${GREEN}✓ Automated backups configured (daily at 2 AM)${NC}"

# Summary
echo -e "\n${GREEN}========================================${NC}"
echo -e "${GREEN}Database Setup Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo -e "\nDatabase Details:"
echo -e "  Name: ${DB_NAME}"
echo -e "  User: ${DB_USER}"
echo -e "  Password: ${DB_PASSWORD}"
echo -e "  Connection URL: postgresql://${DB_USER}:${DB_PASSWORD}@localhost:5432/${DB_NAME}"
echo -e "\n${YELLOW}Important: Save these credentials securely!${NC}"
echo -e "Credentials also saved in: ${CREDENTIALS_FILE}"
echo -e "\nBackup configuration:"
echo -e "  Backup directory: ${BACKUP_DIR}"
echo -e "  Schedule: Daily at 2 AM"
echo -e "  Retention: 7 days"

echo -e "\n${YELLOW}Next step:${NC}"
echo -e "  Run: sudo bash deployment/scripts/setup-environment.sh"

echo -e "\n${GREEN}Done!${NC}"
